/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * LocalID Agent API
 * Localhost identity agent for signing backend challenges with a smartcard or PKCS#11 device.
Does not issue sessions or tokens.

In development, this spec is also served at `GET /openapi.json` when `server.dev_mode` is enabled.

 * OpenAPI spec version: 0.1.0
 */
import { agentFetch } from './mutators';
export interface HealthResponse {
  ok: boolean;
  name: string;
  version: string;
}

export interface Status {
  provider: string;
  ready: boolean;
  cardPresent: boolean;
}

export type SignChallengeRequestPurpose = typeof SignChallengeRequestPurpose[keyof typeof SignChallengeRequestPurpose];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignChallengeRequestPurpose = {
  login: 'login',
} as const;

export interface SignChallengeRequest {
  /** Base64url challenge from your backend */
  challenge: string;
  /** Exact backend URL from allowed_backends */
  backend: string;
  purpose: SignChallengeRequestPurpose;
  /** Must match Origin header */
  origin: string;
}

export interface SignChallengeResponse {
  provider: string;
  algorithm: string;
  challenge: string;
  /** Base64url RSA PKCS#1 v1.5 signature over canonical payload */
  signature: string;
  /** Base64 DER certificate (optional for some providers) */
  certificate?: string;
  /** RFC3339 UTC timestamp used in canonical payload */
  signedAt: string;
}

export interface ErrorResponse {
  error: string;
  message: string;
}

/**
 * Invalid request
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Origin, backend, or purpose not allowed
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Internal server error
 */
export type InternalErrorResponse = ErrorResponse;

/**
 * Content-Type must be application/json
 */
export type UnsupportedMediaTypeResponse = ErrorResponse;

/**
 * Request body exceeds 64 KB
 */
export type PayloadTooLargeResponse = ErrorResponse;

/**
 * Browser origin; must match request body `origin` and allowed_origins config
 */
export type OriginHeaderParameter = string;

export type GetOpenAPISpec200 = { [key: string]: unknown };

/**
 * @summary Agent liveness
 */
export type getHealthResponse200 = {
  data: HealthResponse
  status: 200
}
    
export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
;

export type getHealthResponse = (getHealthResponseSuccess)

export const getGetHealthUrl = () => {


  

  return `/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {
  
  return agentFetch<getHealthResponse>(getGetHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Active provider status
 */
export type getStatusResponse200 = {
  data: Status
  status: 200
}

export type getStatusResponse500 = {
  data: InternalErrorResponse
  status: 500
}
    
export type getStatusResponseSuccess = (getStatusResponse200) & {
  headers: Headers;
};
export type getStatusResponseError = (getStatusResponse500) & {
  headers: Headers;
};

export type getStatusResponse = (getStatusResponseSuccess | getStatusResponseError)

export const getGetStatusUrl = () => {


  

  return `/status`
}

export const getStatus = async ( options?: RequestInit): Promise<getStatusResponse> => {
  
  return agentFetch<getStatusResponse>(getGetStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Signs a canonical JSON payload with the configured provider.
Requires `Origin` header matching `origin` in the body and allowlisted in agent config.

 * @summary Sign a backend challenge
 */
export type signChallengeResponse200 = {
  data: SignChallengeResponse
  status: 200
}

export type signChallengeResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type signChallengeResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type signChallengeResponse413 = {
  data: PayloadTooLargeResponse
  status: 413
}

export type signChallengeResponse415 = {
  data: UnsupportedMediaTypeResponse
  status: 415
}
    
export type signChallengeResponseSuccess = (signChallengeResponse200) & {
  headers: Headers;
};
export type signChallengeResponseError = (signChallengeResponse400 | signChallengeResponse403 | signChallengeResponse413 | signChallengeResponse415) & {
  headers: Headers;
};

export type signChallengeResponse = (signChallengeResponseSuccess | signChallengeResponseError)

export const getSignChallengeUrl = () => {


  

  return `/sign-challenge`
}

export const signChallenge = async (signChallengeRequest: SignChallengeRequest, options?: RequestInit): Promise<signChallengeResponse> => {
  
  return agentFetch<signChallengeResponse>(getSignChallengeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signChallengeRequest,)
  }
);}



/**
 * Returns this OpenAPI specification when `server.dev_mode` is true.
 * @summary OpenAPI document (dev mode only)
 */
export type getOpenAPISpecResponse200 = {
  data: GetOpenAPISpec200
  status: 200
}

export type getOpenAPISpecResponse404 = {
  data: void
  status: 404
}
    
export type getOpenAPISpecResponseSuccess = (getOpenAPISpecResponse200) & {
  headers: Headers;
};
export type getOpenAPISpecResponseError = (getOpenAPISpecResponse404) & {
  headers: Headers;
};

export type getOpenAPISpecResponse = (getOpenAPISpecResponseSuccess | getOpenAPISpecResponseError)

export const getGetOpenAPISpecUrl = () => {


  

  return `/openapi.json`
}

export const getOpenAPISpec = async ( options?: RequestInit): Promise<getOpenAPISpecResponse> => {
  
  return agentFetch<getOpenAPISpecResponse>(getGetOpenAPISpecUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
