/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * LocalID Backend API
 * Reference contract for customer backends integrating with LocalID Agent.
Issue challenges and verify signed proofs. Your backend owns sessions.

 * OpenAPI spec version: 0.1.0
 */
import { backendFetch } from './mutators';
export interface ChallengeResponse {
  /** Base64url random challenge (single use, ~60s TTL) */
  challenge: string;
}

export type VerifyRequestPurpose = typeof VerifyRequestPurpose[keyof typeof VerifyRequestPurpose];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VerifyRequestPurpose = {
  login: 'login',
} as const;

export type VerifyRequestAlgorithm = typeof VerifyRequestAlgorithm[keyof typeof VerifyRequestAlgorithm];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VerifyRequestAlgorithm = {
  RS256: 'RS256',
} as const;

export interface VerifyRequest {
  challenge: string;
  backend: string;
  origin: string;
  purpose: VerifyRequestPurpose;
  provider: string;
  algorithm: VerifyRequestAlgorithm;
  signature: string;
  certificate?: string;
  signedAt: string;
}

export interface VerifyResponse {
  success: boolean;
  user: VerifyUser;
}

export interface VerifyUser {
  id: string;
  name: string;
}

export interface ErrorResponse {
  error: string;
}

/**
 * Invalid request
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Verification failed
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Internal server error
 */
export type InternalErrorResponse = ErrorResponse;

export type CreateChallengeBody = { [key: string]: unknown };

/**
 * @summary Issue a one-time challenge
 */
export type createChallengeResponse200 = {
  data: ChallengeResponse
  status: 200
}

export type createChallengeResponse500 = {
  data: InternalErrorResponse
  status: 500
}
    
export type createChallengeResponseSuccess = (createChallengeResponse200) & {
  headers: Headers;
};
export type createChallengeResponseError = (createChallengeResponse500) & {
  headers: Headers;
};

export type createChallengeResponse = (createChallengeResponseSuccess | createChallengeResponseError)

export const getCreateChallengeUrl = () => {


  

  return `/localid/challenge`
}

export const createChallenge = async (createChallengeBody?: CreateChallengeBody, options?: RequestInit): Promise<createChallengeResponse> => {
  
  return backendFetch<createChallengeResponse>(getCreateChallengeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createChallengeBody,)
  }
);}



/**
 * @summary Verify signed proof and authenticate user
 */
export type verifyProofResponse200 = {
  data: VerifyResponse
  status: 200
}

export type verifyProofResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type verifyProofResponse403 = {
  data: ForbiddenResponse
  status: 403
}
    
export type verifyProofResponseSuccess = (verifyProofResponse200) & {
  headers: Headers;
};
export type verifyProofResponseError = (verifyProofResponse400 | verifyProofResponse403) & {
  headers: Headers;
};

export type verifyProofResponse = (verifyProofResponseSuccess | verifyProofResponseError)

export const getVerifyProofUrl = () => {


  

  return `/localid/verify`
}

export const verifyProof = async (verifyRequest: VerifyRequest, options?: RequestInit): Promise<verifyProofResponse> => {
  
  return backendFetch<verifyProofResponse>(getVerifyProofUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyRequest,)
  }
);}
