// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: localid/v1/protocol.proto

package localidv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignChallengeRequest is the body for POST /sign-challenge.
type SignChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     string                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	Purpose       string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Origin        string                 `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignChallengeRequest) Reset() {
	*x = SignChallengeRequest{}
	mi := &file_localid_v1_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignChallengeRequest) ProtoMessage() {}

func (x *SignChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localid_v1_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignChallengeRequest.ProtoReflect.Descriptor instead.
func (*SignChallengeRequest) Descriptor() ([]byte, []int) {
	return file_localid_v1_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *SignChallengeRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *SignChallengeRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *SignChallengeRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *SignChallengeRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

// SignChallengeResponse is returned by POST /sign-challenge on success.
type SignChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Challenge     string                 `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Certificate   string                 `protobuf:"bytes,5,opt,name=certificate,proto3" json:"certificate,omitempty"`
	SignedAt      string                 `protobuf:"bytes,6,opt,name=signedAt,proto3" json:"signedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignChallengeResponse) Reset() {
	*x = SignChallengeResponse{}
	mi := &file_localid_v1_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignChallengeResponse) ProtoMessage() {}

func (x *SignChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localid_v1_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignChallengeResponse.ProtoReflect.Descriptor instead.
func (*SignChallengeResponse) Descriptor() ([]byte, []int) {
	return file_localid_v1_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *SignChallengeResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SignChallengeResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *SignChallengeResponse) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *SignChallengeResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignChallengeResponse) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *SignChallengeResponse) GetSignedAt() string {
	if x != nil {
		return x.SignedAt
	}
	return ""
}

// Status is returned by GET /status.
type Status struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Provider    string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Ready       bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	CardPresent bool                   `protobuf:"varint,3,opt,name=cardPresent,proto3" json:"cardPresent,omitempty"`
	// Human-readable detail when ready/cardPresent is false (e.g. missing PKCS#11 module).
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_localid_v1_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_localid_v1_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_localid_v1_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Status) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *Status) GetCardPresent() bool {
	if x != nil {
		return x.CardPresent
	}
	return false
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HealthResponse is returned by GET /health.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_localid_v1_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localid_v1_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_localid_v1_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_localid_v1_protocol_proto protoreflect.FileDescriptor

const file_localid_v1_protocol_proto_rawDesc = "" +
	"\n" +
	"\x19localid/v1/protocol.proto\x12\n" +
	"localid.v1\"\x80\x01\n" +
	"\x14SignChallengeRequest\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\tR\tchallenge\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\tR\x06origin\"\xcb\x01\n" +
	"\x15SignChallengeResponse\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x1c\n" +
	"\tchallenge\x18\x03 \x01(\tR\tchallenge\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x12 \n" +
	"\vcertificate\x18\x05 \x01(\tR\vcertificate\x12\x1a\n" +
	"\bsignedAt\x18\x06 \x01(\tR\bsignedAt\"v\n" +
	"\x06Status\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12 \n" +
	"\vcardPresent\x18\x03 \x01(\bR\vcardPresent\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"N\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversionB\xc3\x01\n" +
	"\x0ecom.localid.v1B\rProtocolProtoP\x01ZYgithub.com/rqc-icu/localid-agent/services/agent/internal/protocol/pb/localid/v1;localidv1\xa2\x02\x03LXX\xaa\x02\n" +
	"Localid.V1\xca\x02\n" +
	"Localid\\V1\xe2\x02\x16Localid\\V1\\GPBMetadata\xea\x02\vLocalid::V1b\x06proto3"

var (
	file_localid_v1_protocol_proto_rawDescOnce sync.Once
	file_localid_v1_protocol_proto_rawDescData []byte
)

func file_localid_v1_protocol_proto_rawDescGZIP() []byte {
	file_localid_v1_protocol_proto_rawDescOnce.Do(func() {
		file_localid_v1_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_localid_v1_protocol_proto_rawDesc), len(file_localid_v1_protocol_proto_rawDesc)))
	})
	return file_localid_v1_protocol_proto_rawDescData
}

var file_localid_v1_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_localid_v1_protocol_proto_goTypes = []any{
	(*SignChallengeRequest)(nil),  // 0: localid.v1.SignChallengeRequest
	(*SignChallengeResponse)(nil), // 1: localid.v1.SignChallengeResponse
	(*Status)(nil),                // 2: localid.v1.Status
	(*HealthResponse)(nil),        // 3: localid.v1.HealthResponse
}
var file_localid_v1_protocol_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_localid_v1_protocol_proto_init() }
func file_localid_v1_protocol_proto_init() {
	if File_localid_v1_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_localid_v1_protocol_proto_rawDesc), len(file_localid_v1_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_localid_v1_protocol_proto_goTypes,
		DependencyIndexes: file_localid_v1_protocol_proto_depIdxs,
		MessageInfos:      file_localid_v1_protocol_proto_msgTypes,
	}.Build()
	File_localid_v1_protocol_proto = out.File
	file_localid_v1_protocol_proto_goTypes = nil
	file_localid_v1_protocol_proto_depIdxs = nil
}
